name: Reset to Yesterday's Copy

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Manually trigger workflow

jobs:
  reset_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find yesterday's commit
        id: yesterday_commit
        run: |
          YESTERDAY=$(date -d "yesterday" +%Y-%m-%d)
          git fetch --depth=1 origin "+refs/heads/*:refs/remotes/origin/*"
          YESTERDAY_COMMIT=$(git log --before="$YESTERDAY 00:00:00" --format="%H" -1)
          echo "::set-output name=commit_hash::$YESTERDAY_COMMIT"

      - name: Reset to yesterday's copy
        if: steps.yesterday_commit.outputs.commit_hash != ''
        run: |
          git reset --hard ${{ steps.yesterday_commit.outputs.commit_hash }}
          git push --force
